### PR TITLE
improve wgs84 support

### PR DESCRIPTION
**Pull request by darinacosta**
These changes were originally submitted in PR https://github.com/ROGUE-JCTD/MapLoom/pull/186 and have since been improved.

- <b>This branch uses OpenLayers v3.13</b>.
- The map view pulls its projection value from the configuration service and reprojects layers on the fly based on this attribute. This allows WGS84 to be projected on the client side.
- OpenLayers doesn't support the bindTo method beyond v7. bindTo was being used in common/diff/FeatureDiffService to sync map views. This branch removes bindTo and makes diff maps share the common/map/MapService map view.
- The map uses a different view if the config 'projection' value == 'EPSG:4326'.

### CODE REVIEW

**Comment by jdgarrett** [comment]
I am seeing an error in the feature diff.

screen shot 2016-02-29 at 6 43 49 pm

To reproduce:
1) View history of layer
2) Click a commit
3) Click on show changes
4) Close feature diff dialog
3) Click on show changes again

**Comment by darinacosta** [comment]
@jdgarrett I'm unable to reproduce this error but will continue to investigate. Thank you!

**Comment by darinacosta** [comment]
@jdgarrett what browser are you using when you get this error? And are you closing the diff dialogue by hitting [X] or 'Cancel'? Thank you.

**Comment by jdgarrett** [comment]
I am using chrome and closing out by hitting the [X] button.

**Comment by jdgarrett** [comment]
Here are the stack traces:
https://gist.github.com/jdgarrett/581021bc7f2f517da6a6

**Comment by darinacosta** [comment]
@jdgarrett The listener error should now be fixed. It was being caused by the featurePanel.featureLayer in the feature diff service getting added twice. Please let me know if it's still happening on your end. Thank you for your patience.

**Comment by jdgarrett** [comment]
The error is now fixed, but I encountered another issue (different steps):
screen shot 2016-03-01 at 6 48 49 pm
Steps to reproduce:
1) View history of layer
2) Click a commit that modified a feature
3) Click on show changes for modified feature
4) Close feature diff dialog
5) Click a commit that added a feature
6) Click on show changes for an added feature
7) Close feature diff dialog
8) Click on the commit that modified a feature
9) Click on show changes for the modified feature.

It does not seem to happen if you didn't view a modified feature before viewing an added feature.  Thanks for the quick updates!

**Comment by darinacosta** [comment]
@jdgarrett Got another one for ya! I did everything I could to try and break the diff functionality and was unable. Very sorry if you've got to kick it back again! I used 'ng-show' rather than 'ng-if' to control the diff view in order to allow OpenLayers to inject the map into the div before it gets displayed:

https://github.com/ROGUE-JCTD/MapLoom/pull/188/files#diff-19da7903138feeb6d65d54915a51240cR5

**Comment by jdgarrett** [comment]
All working now, thanks for the fixes!

**Pull request merged**
